In [ ]:
!pip install --upgrade amltk
!pip install autogluon
!pip install umap-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 186.5/186.5 kB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for amltk: filename=amltk-1.12.0-py3-none-any.whl size=221562 sha256=3df45d86b98c2b7fefbda490cc543cc22b029449651b6d870fadf8c6411631c0
  Stored in directory: /root/.cache/pip/wheels/be/01/36/afeeed4ee1e734444a32b44d14a27054a6d707be8d0aacb8f8
Successfully built amltk
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.5/308.5 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.5/427.5 kB 13.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.1/147.1 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 26.9 MB/s eta 0:00:00
     ━━━━━

In [ ]:
import pandas as pd
from scipy.io import arff
import numpy as np
import matplotlib.pyplot as plt
data = arff.loadarff('EEG Eye State.arff')
train= pd.DataFrame(data[0])
train.head(6656)

In [ ]:
X = train.iloc[:, :-1].values
y = train.iloc[:, -1].values

In [ ]:
print(X)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:-1])
X[:, 1:-1] = imputer.transform(X[:, 1:-1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X)

[[4329.23 4009.23 4289.23 ... 4280.51 4635.9  4393.85]
 [4324.62 4004.62 4293.85 ... 4279.49 4632.82 4384.1 ]
 [4327.69 4006.67 4295.38 ... 4282.05 4628.72 4389.23]
 ...
 [4277.44 3990.77 4246.67 ... 4257.95 4591.79 4339.49]
 [4284.62 3991.79 4251.28 ... 4267.18 4596.41 4350.77]
 [4287.69 3997.44 4260.   ... 4274.36 4597.95 4350.77]]


In [ ]:
print(X_train)

[[4284.1  3990.26 4267.18 ... 4289.74 4624.62 4362.05]
 [4301.03 3982.56 4272.82 ... 4287.18 4588.72 4364.1 ]
 [4298.97 4050.26 4277.44 ... 4287.69 4606.67 4351.28]
 ...
 [4284.1  3982.56 4264.62 ... 4258.97 4594.36 4354.87]
 [4361.03 4062.05 4325.64 ... 4330.26 4663.59 4411.28]
 [4276.92 4001.54 4256.92 ... 4274.36 4588.72 4333.33]]


In [ ]:
print(X_test)

[[4270.77 4017.44 4258.97 ... 4286.15 4617.95 4342.05]
 [4336.92 4034.36 4300.   ... 4305.13 4626.15 4392.31]
 [4298.46 3992.82 4264.1  ... 4289.74 4599.49 4380.  ]
 ...
 [4294.87 3995.38 4272.31 ... 4278.46 4587.69 4348.72]
 [4318.97 4009.23 4278.97 ... 4291.79 4620.51 4389.74]
 [4288.21 3984.1  4262.56 ... 4261.03 4592.31 4355.38]]


In [ ]:
print(y_train)

[0 1 0 ... 0 0 0]


In [ ]:
print(y_test)

[1 0 0 ... 1 1 1]


In [ ]:
!pip install umap-learn
import pandas as pd
from scipy.io import arff
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import umap
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# UMAP uygula
umap_model = umap.UMAP(n_components=2, random_state=42)
X_umap = umap_model.fit_transform(X_scaled)

# Görselleştirme
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_umap[:, 0], X_umap[:, 1], c=y, cmap='viridis', alpha=0.5)
plt.title('EEG-EYESTATE UMAP')
plt.xlabel('Birinci Boyut')
plt.ylabel('İkinci Boyut')
plt.colorbar(scatter, label='Etiket')
plt.show()


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.01532985 -0.41043601  0.06680816 ...  0.27767273  0.00525018
  -0.00898727]
 [-0.00925282 -0.57129895  0.19027327 ...  0.21121715 -0.02132655
  -0.00867187]
 [-0.00999226  0.84304145  0.29140958 ...  0.22445635 -0.00803818
  -0.01064428]
 ...
 [-0.01532985 -0.57129895  0.01076726 ... -0.52109219 -0.01715126
  -0.01009194]
 [ 0.01228419  1.08934977  1.34655467 ...  1.32953997  0.03409962
  -0.00141301]
 [-0.01790711 -0.17478225 -0.15779326 ... -0.12157994 -0.02132655
  -0.01340597]]


In [ ]:
print(X_test)

[[-2.01146504e-02  1.57389275e-01 -1.12916761e-01 ...  1.84479164e-01
   3.12385373e-04 -1.20643605e-02]
 [ 3.62989876e-03  5.10869919e-01  7.85270022e-01 ...  6.77184992e-01
   6.38283466e-03 -4.33162883e-03]
 [-1.01753221e-02 -3.56954309e-01 -6.16049063e-04 ...  2.77672732e-01
  -1.33535285e-02 -6.22557883e-03]
 ...
 [-1.14639530e-02 -3.03472604e-01  1.79108871e-01 ... -1.51471694e-02
  -2.20890531e-02 -1.10381504e-02]
 [-2.81325554e-03 -1.41282236e-02  3.24902778e-01 ...  3.30889115e-01
   2.20755003e-03 -4.72703513e-03]
 [-1.38545606e-02 -5.39126366e-01 -3.43281535e-02 ... -4.67616220e-01
  -1.86688731e-02 -1.00134788e-02]]


Logistic Regression


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 0]
 [1 0]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

[[1237  388]
 [ 869  502]]
Accuracy: 0.5804405874499332
Precision: 0.5640449438202247
Recall: 0.3661560904449307
F1 Score: 0.44405130473241927


K NEAREST NEIGHBOURS

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

[[1513  112]
 [ 149 1222]]
Accuracy: 0.9128838451268357
Precision: 0.9160419790104948
Recall: 0.8913202042304887
F1 Score: 0.9035120147874307


SUPPORT VECTOR MACHİNE

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

[[1439  186]
 [ 992  379]]
Accuracy: 0.6068090787716955
Precision: 0.6707964601769911
Recall: 0.2764405543398979
F1 Score: 0.3915289256198347


KERNEL - SVM

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

NAİVE BAYES


In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

DECISION TREE CLASSIFICATION

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

RANDOM FOREST CLASSIFICATION

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

KNN Hiperparametre degişiklikleri

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Model ve parametreler
classifier = KNeighborsClassifier()
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'metric': ['minkowski', 'euclidean', 'manhattan'],
    'p': [1, 2]
}

# GridSearchCV
grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=10, n_jobs=-1, scoring='accuracy')
grid_search.fit(X_train, y_train)

# En iyi parametreler
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# En iyi model ile tahmin
best_classifier = grid_search.best_estimator_
y_pred = best_classifier.predict(X_test)

# Tahmin ve gerçek değerleri birleştirip yazdırma
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Performans metrikleri
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# Tüm parametreler ve özellikler
print("\nBest Estimator Parameters:")
print(best_classifier.get_params())

# GridSearchCV sonuçları
print("\nGrid Search CV Results:")
print(grid_search.cv_results_)



/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()


Best Parameters: {'metric': 'minkowski', 'n_neighbors': 3, 'p': 1}
[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]
Confusion Matrix:
 [[1522  103]
 [ 123 1248]]
Accuracy: 0.92456608811749
Precision: 0.923760177646188
Recall: 0.9102844638949672
F1 Score: 0.916972814107274

Best Estimator Parameters:
{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}

Grid Search CV Results:
{'mean_fit_time': array([0.06890817, 0.062079  , 0.07220099, 0.04898169, 0.05355406,
       0.07636166, 0.05117953, 0.03031588, 0.03086088, 0.03095696,
       0.03041329, 0.06055133, 0.05796275, 0.03073795, 0.02980313,
       0.03030205, 0.03031611, 0.03070726, 0.03658276, 0.0639739 ,
       0.03656642, 0.03065367, 0.03101256, 0.03071122, 0.05066385,
       0.04338596, 0.03063543, 0.03078041, 0.03097761, 0.0584609 ]), 'std_fit_time': array([0.02814992, 0.01986437, 0.02203851, 0.01495229, 0.01258063,
       0.02146137, 0.

Feature Engineering


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np
from sklearn.preprocessing import StandardScaler

# Feature scaling ve KNeighborsClassifier pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures()),
    ('knn', KNeighborsClassifier())
])

# GridSearchCV için parametreler
param_grid = {
    'poly__degree': [1, 2, 3],
    'knn__n_neighbors': [3, 5, 7, 9, 11],
    'knn__metric': ['minkowski', 'euclidean', 'manhattan'],
    'knn__p': [1, 2]
}

# GridSearchCV
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=10, n_jobs=-1, scoring='accuracy')
grid_search.fit(X_train, y_train)

# En iyi parametreler
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# En iyi model ile tahmin
best_classifier = grid_search.best_estimator_
y_pred = best_classifier.predict(X_test)

# Tahmin ve gerçek değerleri birleştirip yazdırma
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Performans metrikleri
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()


Best Parameters: {'knn__metric': 'minkowski', 'knn__n_neighbors': 3, 'knn__p': 1, 'poly__degree': 1}
[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]
Confusion Matrix:
 [[1522  103]
 [ 123 1248]]
Accuracy: 0.92456608811749
Precision: 0.923760177646188
Recall: 0.9102844638949672
F1 Score: 0.916972814107274


Ensemble Methods

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Base estimators
estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('tree', DecisionTreeClassifier(max_depth=3)),
    ('svc', SVC(kernel='rbf', probability=True))
]

# StackingClassifier
classifier = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
classifier.fit(X_train, y_train)

# Tahmin
y_pred = classifier.predict(X_test)

# Tahmin ve gerçek değerleri birleştirip yazdırma
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Performans metrikleri
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision:", precision)
recall = recall_score(y_test, y_pred)
print("Recall:", recall)
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)


[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]
Confusion Matrix:
 [[1513  112]
 [ 147 1224]]
Accuracy: 0.9135514018691588
Precision: 0.9161676646706587
Recall: 0.8927789934354485
F1 Score: 0.9043221278167713


AUTOML Kısmı


In [ ]:
!pip install -U scikit-learn
# Autogluon'u yükleyin
!pip install -q autogluon

# Gerekli kütüphaneleri içe aktarın
import pandas as pd
from scipy.io import arff
from autogluon.tabular import TabularDataset, TabularPredictor

# Veri setini yükleyin
data = arff.loadarff('EEG Eye State.arff')
train = pd.DataFrame(data[0])

# Veri setini Autogluon'un kullanabileceği formata dönüştürün
train_data = TabularDataset(train)

# Modeli eğitin
predictor = TabularPredictor(label='eyeDetection').fit(train_data)

# Sonuçları görselleştirin
leaderboard = predictor.leaderboard(train_data)
print(leaderboard)


  Using cached scikit_learn-1.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.4.0
    Uninstalling scikit-learn-1.4.0:
      Successfully uninstalled scikit-learn-1.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-core 1.1.0 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.
autogluon-features 1.1.0 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.
autogluon-multimodal 1.1.0 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.
autogluon-tabular 1.1.0 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.


No path specified. Models will be saved in: "AutogluonModels/ag-20240520_155100"
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20240520_155100"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sun Apr 28 14:29:16 UTC 2024
C

[1000]	valid_set's binary_error: 0.0841121
[2000]	valid_set's binary_error: 0.0667557
[3000]	valid_set's binary_error: 0.0574099
[4000]	valid_set's binary_error: 0.0520694
[5000]	valid_set's binary_error: 0.046729
[6000]	valid_set's binary_error: 0.0460614
[7000]	valid_set's binary_error: 0.0487316


	0.9553	 = Validation score   (accuracy)
	17.67s	 = Training   runtime
	1.57s	 = Validation runtime
Fitting model: LightGBM ...


[1000]	valid_set's binary_error: 0.052737


	0.9499	 = Validation score   (accuracy)
	4.71s	 = Training   runtime
	0.2s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.9386	 = Validation score   (accuracy)
	7.49s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.9359	 = Validation score   (accuracy)
	10.16s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost ...
	0.9593	 = Validation score   (accuracy)
	64.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.9486	 = Validation score   (accuracy)
	3.01s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.9513	 = Validation score   (accuracy)
	3.21s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 9: early stopping
	0.7043	 = Validation score   (accuracy)
	19.91s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ...
	0.9539	 = Validation score   

[1000]	valid_set's binary_error: 0.0420561
[2000]	valid_set's binary_error: 0.0353805


	0.9646	 = Validation score   (accuracy)
	17.84s	 = Training   runtime
	0.83s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.8, 'KNeighborsUnif': 0.2}
	0.9866	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 214.1s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240520_155100")


                  model  score_test  score_val eval_metric  pred_time_test  \
0        KNeighborsDist    0.997530   0.975300    accuracy        1.202426   
1   WeightedEnsemble_L2    0.997130   0.986649    accuracy        1.388415   
2        NeuralNetTorch    0.996862   0.985981    accuracy        0.143190   
3         LightGBMLarge    0.996462   0.964619    accuracy       10.552741   
4              CatBoost    0.995928   0.959279    accuracy        0.098246   
5               XGBoost    0.995394   0.953939    accuracy        2.077235   
6        ExtraTreesEntr    0.995127   0.951268    accuracy        0.997418   
7              LightGBM    0.994993   0.949933    accuracy        1.618742   
8        ExtraTreesGini    0.994860   0.948598    accuracy        1.144090   
9      RandomForestGini    0.993858   0.938585    accuracy        0.810786   
10     RandomForestEntr    0.993591   0.935915    accuracy        0.767434   
11           LightGBMXT    0.988451   0.955274    accuracy      

In [ ]:
# Sonuçları görselleştirin
leaderboard = predictor.leaderboard(train_data)
print(leaderboard)

# En iyi modelin adını alın
best_model_name = predictor.leaderboard(train_data).iloc[0, 0]
print("En iyi model:", best_model_name)
best_model = predictor._trainer.load_model(best_model_name)
print("En iyi modelin hiperparametreleri:", best_model.params)
# Scikit-learn KNeighborsClassifier modelini inceleyin
knn_model = best_model.model

# Modelin detaylarını yazdırın
print(knn_model)
print("Hiperparametreler:", knn_model.get_params())
# WeightedEnsemble_L2 modelinin içindeki modelleri öğrenin
ensemble_model_name = 'WeightedEnsemble_L2'
ensemble_model = predictor._trainer.load_model(ensemble_model_name)

# Ensemble modeli içinde kullanılan alt modellerin isimleri
base_model_names = ensemble_model.base_model_names
print("WeightedEnsemble_L2 modeli içinde kullanılan alt modeller:", base_model_names)


                  model  score_test  score_val eval_metric  pred_time_test  \
0        KNeighborsDist    0.997530   0.975300    accuracy        1.443955   
1   WeightedEnsemble_L2    0.997130   0.986649    accuracy        2.389382   
2        NeuralNetTorch    0.996862   0.985981    accuracy        0.207567   
3         LightGBMLarge    0.996462   0.964619    accuracy       14.405220   
4              CatBoost    0.995928   0.959279    accuracy        0.119359   
5               XGBoost    0.995394   0.953939    accuracy        4.635782   
6        ExtraTreesEntr    0.995127   0.951268    accuracy        2.201980   
7              LightGBM    0.994993   0.949933    accuracy        2.624464   
8        ExtraTreesGini    0.994860   0.948598    accuracy        1.477910   
9      RandomForestGini    0.993858   0.938585    accuracy        1.378740   
10     RandomForestEntr    0.993591   0.935915    accuracy        1.320895   
11           LightGBMXT    0.988451   0.955274    accuracy      